// Registro de iconos. Unica fuente de verdad de toda la interfaz.
//
// Cada nombre del dominio apunta a un icono de Lucide, la biblioteca que trae
// shadcn/ui. Cambiar el icono de "citas" por otro es editar una linea de este
// archivo y verlo en todas las pantallas, sin tocar ni un componente: el resto
// de la aplicacion no importa Lucide, pide un nombre a `Icon.tsx`.
//
// Todos comparten el mismo trazo y se dibujan con el color del texto que los
// rodea, para que hereden el tono de donde se usen.

import {
  AlignLeft,
  Banknote,
  Calendar,
  CalendarCheck2,
  CalendarDays,
  ChartColumnIncreasing,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleX,
  ClipboardList,
  Clock,
  Dna,
  Download,
  Eye,
  EyeOff,
  FolderHeart,
  Hash,
  HeartPulse,
  House,
  IdCard,
  ListFilter,
  LockKeyhole,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Microchip,
  NotebookPen,
  Palette,
  PawPrint,
  Phone,
  Pill,
  Plus,
  Repeat,
  Ruler,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  SunMoon,
  TriangleAlert,
  UserCog,
  UserRound,
  UserRoundPlus,
  VenusAndMars,
  Wallet,
  Weight,
} from 'lucide-react'

export const ICONS = {
  // Marca.
  huella: PawPrint,

  // Navegacion y dominio. Tres nombres comparten icono a proposito: lo que los
  // separa es el significado, no el dibujo.
  inicio: House,
  menu: Menu,
  mascota: PawPrint,
  agenda: CalendarDays,
  cita: CalendarCheck2,
  emergencia: TriangleAlert,
  personal: UserRound,
  cliente: UserRound,
  perfil: UserRound,
  ubicacion: MapPin,
  horario: Clock,

  // Acciones.
  agregar: Plus,
  confirmar: Check,
  cancelar: CircleX,
  salir: LogOut,
  entrar: LogIn,
  registrarse: UserRoundPlus,
  correo: Mail,
  ver: Eye,
  ocultar: EyeOff,
  buscar: Search,
  pago: Banknote,
  descargar: Download,
  anterior: ChevronLeft,
  siguiente: ChevronRight,
  desplegar: ChevronsUpDown,

  // Estado.
  activo: Circle,
  alerta: CircleAlert,
  indicadores: ChartColumnIncreasing,
  salud: HeartPulse,
  carpeta: FolderHeart,
  engranaje: Settings,
  permisos: ShieldCheck,

  // Campos de formulario: acompañan a la etiqueta, no la reemplazan.
  telefono: Phone,
  documento: IdCard,
  fecha: Calendar,
  candado: LockKeyhole,
  numero: Hash,
  nota: NotebookPen,
  mensaje: MessageSquare,
  descripcion: AlignLeft,
  filtro: ListFilter,
  peso: Weight,
  altura: Ruler,
  color: Palette,
  microchip: Microchip,
  temperamento: Smile,
  sexo: VenusAndMars,
  raza: Dna,
  alergia: ShieldAlert,
  estrella: Star,
  ia: Sparkles,
  diagnostico: Stethoscope,
  tratamiento: Pill,
  vacuna: Syringe,
  registroClinico: ClipboardList,
  medioDePago: Wallet,
  tipoDeCuenta: UserCog,
  repetir: Repeat,
  turno: SunMoon,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
