/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movimientos de las cuentas */
        get: operations["read_activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar citas */
        get: operations["list_appointments_api_v1_appointments_get"];
        put?: never;
        /** Reservar una cita */
        post: operations["book_appointment_api_v1_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/emergency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abrir una emergencia ahora */
        post: operations["open_emergency_api_v1_appointments_emergency_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Motivos de consulta reservables */
        get: operations["list_types_api_v1_appointments_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancelar una cita */
        post: operations["cancel_appointment_api_v1_appointments__appointment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dar por completada una cita */
        post: operations["complete_appointment_api_v1_appointments__appointment_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar una cita */
        post: operations["confirm_appointment_api_v1_appointments__appointment_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pedir un enlace de recuperación de contraseña */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obtener un token de acceso */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cuenta que emitió la petición */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar el perfil propio */
        patch: operations["update_current_user_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autorregistro de un cliente */
        post: operations["register_client_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fijar una contraseña nueva con el enlace recibido */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agenda de un veterinario */
        get: operations["list_slots_of_veterinarian_api_v1_availability_get"];
        put?: never;
        /** Publicar un tramo de disponibilidad propio */
        post: operations["publish_slot_api_v1_availability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mi agenda publicada */
        get: operations["list_my_slots_api_v1_availability_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Retirar un tramo propio */
        delete: operations["withdraw_slot_api_v1_availability__slot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar clientes */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sondeo de vida */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/medical-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historia clínica de una mascota */
        get: operations["list_clinical_entries_api_v1_medical_records_get"];
        put?: never;
        /** Agregar una entrada a la historia clínica */
        post: operations["add_clinical_entry_api_v1_medical_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/medical-records/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Quitar un adjunto de la historia clínica */
        delete: operations["delete_attachment_api_v1_medical_records_attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/medical-records/{entry_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjuntar un archivo a una entrada de la historia clínica */
        post: operations["upload_attachment_api_v1_medical_records__entry_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar pagos */
        get: operations["list_payments_api_v1_payments_get"];
        put?: never;
        /** Registrar un pago */
        post: operations["register_payment_api_v1_payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cuánto se cobró y por qué medio */
        get: operations["payment_report_api_v1_payments_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anular un pago registrado por error */
        post: operations["void_payment_api_v1_payments__payment_id__void_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar mascotas de un cliente */
        get: operations["list_pets_of_owner_api_v1_pets_get"];
        put?: never;
        /** Registrar una mascota propia */
        post: operations["register_pet_api_v1_pets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar mis mascotas */
        get: operations["list_my_pets_api_v1_pets_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets/{pet_id}/correct-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corregir el estado de una mascota (personal de la clínica) */
        patch: operations["correct_pet_status_api_v1_pets__pet_id__correct_status_patch"];
        trace?: never;
    };
    "/api/v1/pets/{pet_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Dar de baja o reactivar una mascota propia */
        patch: operations["change_pet_status_api_v1_pets__pet_id__status_patch"];
        trace?: never;
    };
    "/api/v1/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar el personal */
        get: operations["list_staff_api_v1_staff_get"];
        put?: never;
        /** Dar de alta un veterinario */
        post: operations["register_staff_api_v1_staff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{user_id}/emergency-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Habilitar o quitar el respaldo de emergencias */
        post: operations["toggle_emergency_coverage_api_v1_staff__user_id__emergency_coverage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{user_id}/guard-duty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poner o sacar del turno de guardia */
        post: operations["toggle_guard_duty_api_v1_staff__user_id__guard_duty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activar o desactivar una cuenta */
        patch: operations["change_user_status_api_v1_users__user_id__status_patch"];
        trace?: never;
    };
    "/api/v1/veterinarians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Veterinarios que atienden */
        get: operations["list_veterinarians_api_v1_veterinarians_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenResponse */
        AccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * ActivityKind
         * @description Qué ocurrió.
         *
         *     El original guardaba una frase armada a mano, del estilo "Reservó cita de
         *     tipo Consulta general". Eso impide filtrar y contar: cada variante del
         *     texto es un valor distinto. Acá el tipo es un código estable y la frase
         *     legible se arma al mostrarla, así que cambiar la redacción no rompe el
         *     historial.
         * @enum {string}
         */
        ActivityKind: "signed_in" | "client_registered" | "profile_updated" | "staff_registered" | "user_status_changed" | "guard_duty_toggled" | "pet_registered" | "pet_status_changed" | "pet_status_corrected" | "slot_published" | "slot_withdrawn" | "appointment_booked" | "emergency_opened" | "appointment_confirmed" | "appointment_completed" | "appointment_cancelled" | "clinical_entry_added" | "attachment_uploaded" | "attachment_deleted" | "payment_registered" | "payment_voided";
        /** ActivityPageResponse */
        ActivityPageResponse: {
            /** Items */
            items: components["schemas"]["ActivityResponse"][];
            /** Total */
            total: number;
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Detail */
            detail: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Kind Label */
            kind_label: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
            user_role: components["schemas"]["Role"];
        };
        /** AddClinicalEntryRequest */
        AddClinicalEntryRequest: {
            /** Appointment Id */
            appointment_id?: number | null;
            /**
             * Diagnosis
             * @default
             */
            diagnosis: string;
            kind: components["schemas"]["EntryKind"];
            /** Notes */
            notes: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Pet Id */
            pet_id: number;
            /**
             * Treatment
             * @default
             */
            treatment: string;
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** AppointmentPageResponse */
        AppointmentPageResponse: {
            /** Items */
            items: components["schemas"]["AppointmentResponse"][];
            /** Total */
            total: number;
        };
        /** AppointmentResponse */
        AppointmentResponse: {
            /** Appointment Type Id */
            appointment_type_id: number;
            /** Cancellation Reason */
            cancellation_reason: string;
            /** Client Id */
            client_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Id */
            id: number;
            /** Pet Id */
            pet_id: number;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            status: components["schemas"]["AppointmentStatus"];
            /** Status Label */
            status_label: string;
            /** Updated By */
            updated_by: number | null;
            /** Veterinarian Id */
            veterinarian_id: number;
        };
        /**
         * AppointmentStatus
         * @enum {string}
         */
        AppointmentStatus: "pending" | "confirmed" | "completed" | "cancelled";
        /** AppointmentTypeListResponse */
        AppointmentTypeListResponse: {
            /** Items */
            items: components["schemas"]["AppointmentTypeResponse"][];
            /** Total */
            total: number;
        };
        /** AppointmentTypeResponse */
        AppointmentTypeResponse: {
            /** Duration Minutes */
            duration_minutes: number;
            /** Id */
            id: number;
            /** Is Emergency */
            is_emergency: boolean;
            /** Name */
            name: string;
            /** Price */
            price: string;
        };
        /** AttachmentResponse */
        AttachmentResponse: {
            /** Clinical Entry Id */
            clinical_entry_id: number;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Size Bytes */
            size_bytes: number;
            /** Uploaded By */
            uploaded_by: number;
            /** Url */
            url: string;
        };
        /** Body_upload_attachment_api_v1_medical_records__entry_id__attachments_post */
        Body_upload_attachment_api_v1_medical_records__entry_id__attachments_post: {
            /** File */
            file: string;
        };
        /** BookAppointmentRequest */
        BookAppointmentRequest: {
            /** Appointment Type Id */
            appointment_type_id: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Pet Id */
            pet_id: number;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Veterinarian Id */
            veterinarian_id: number;
        };
        /** CancelAppointmentRequest */
        CancelAppointmentRequest: {
            /** Reason */
            reason: string;
        };
        /** ChangePetStatusRequest */
        ChangePetStatusRequest: {
            /** Is Active */
            is_active: boolean;
        };
        /** ChangeUserStatusRequest */
        ChangeUserStatusRequest: {
            /** Is Active */
            is_active: boolean;
        };
        /** ClientPageResponse */
        ClientPageResponse: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
        };
        /** ClinicalEntryPageResponse */
        ClinicalEntryPageResponse: {
            /** Items */
            items: components["schemas"]["ClinicalEntryResponse"][];
            /** Total */
            total: number;
        };
        /** ClinicalEntryResponse */
        ClinicalEntryResponse: {
            /** Appointment Id */
            appointment_id: number | null;
            /** Attachments */
            attachments: components["schemas"]["AttachmentResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Diagnosis */
            diagnosis: string;
            /** Id */
            id: number;
            kind: components["schemas"]["EntryKind"];
            /** Kind Label */
            kind_label: string;
            /** Notes */
            notes: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Pet Id */
            pet_id: number;
            /** Treatment */
            treatment: string;
            /** Veterinarian Id */
            veterinarian_id: number;
            /** Weight Kg */
            weight_kg: string | null;
        };
        /** CorrectPetStatusRequest */
        CorrectPetStatusRequest: {
            /** Is Active */
            is_active: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * EntryKind
         * @enum {string}
         */
        EntryKind: "consultation" | "vaccine" | "surgery" | "follow_up" | "other";
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Respuesta del sondeo de vida.
         *
         *     Está tipada, y no devuelta como diccionario suelto, para que el esquema
         *     OpenAPI describa los campos y el frontend derive el tipo exacto.
         */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** MethodTotalResponse */
        MethodTotalResponse: {
            /** Count */
            count: number;
            method: components["schemas"]["PaymentMethod"];
            /** Method Label */
            method_label: string;
            /** Total */
            total: string;
        };
        /** OpenEmergencyRequest */
        OpenEmergencyRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Pet Id */
            pet_id: number;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "cash" | "yape" | "bank_transfer" | "other";
        /** PaymentPageResponse */
        PaymentPageResponse: {
            /** Items */
            items: components["schemas"]["PaymentResponse"][];
            /** Total */
            total: number;
        };
        /** PaymentReportResponse */
        PaymentReportResponse: {
            /** Grand Total */
            grand_total: string;
            /** Items */
            items: components["schemas"]["MethodTotalResponse"][];
        };
        /** PaymentResponse */
        PaymentResponse: {
            /** Amount */
            amount: string;
            /** Appointment Id */
            appointment_id: number;
            /** Client Id */
            client_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Voided */
            is_voided: boolean;
            method: components["schemas"]["PaymentMethod"];
            /** Method Label */
            method_label: string;
            /** Notes */
            notes: string;
            /**
             * Paid At
             * Format: date-time
             */
            paid_at: string;
            /** Reference */
            reference: string;
            /** Registered By */
            registered_by: number;
            /** Void Reason */
            void_reason: string;
            /** Voided At */
            voided_at: string | null;
        };
        /** PetPageResponse */
        PetPageResponse: {
            /** Items */
            items: components["schemas"]["PetResponse"][];
            /** Total */
            total: number;
        };
        /** PetResponse */
        PetResponse: {
            /** Age In Years */
            age_in_years: number;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Breed */
            breed: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Owner Id */
            owner_id: number;
            /** Species */
            species: string;
        };
        /** PublishSlotRequest */
        PublishSlotRequest: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** RegisterClientRequest */
        RegisterClientRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Password */
            password: string;
            /**
             * Phone
             * @default
             */
            phone: string;
        };
        /** RegisterPaymentRequest */
        RegisterPaymentRequest: {
            /** Amount */
            amount: number | string;
            /** Appointment Id */
            appointment_id: number;
            method: components["schemas"]["PaymentMethod"];
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Reference
             * @default
             */
            reference: string;
        };
        /** RegisterPetRequest */
        RegisterPetRequest: {
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Breed */
            breed: string;
            /** Name */
            name: string;
            /** Species */
            species: string;
        };
        /** RegisterStaffRequest */
        RegisterStaffRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Password */
            password: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            role: components["schemas"]["Role"];
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "client" | "veterinarian" | "emergency_veterinarian";
        /** SlotListResponse */
        SlotListResponse: {
            /** Items */
            items: components["schemas"]["SlotResponse"][];
            /** Total */
            total: number;
        };
        /** SlotResponse */
        SlotResponse: {
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Id */
            id: number;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Veterinarian Id */
            veterinarian_id: number;
        };
        /** ToggleEmergencyCoverageRequest */
        ToggleEmergencyCoverageRequest: {
            /** Can Cover Emergencies */
            can_cover_emergencies: boolean;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** New Password */
            new_password?: string | null;
            /**
             * Phone
             * @default
             */
            phone: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Can Cover Emergencies */
            can_cover_emergencies: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            /** Phone */
            phone: string;
            role: components["schemas"]["Role"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VeterinarianListResponse */
        VeterinarianListResponse: {
            /** Items */
            items: components["schemas"]["VeterinarianResponse"][];
            /** Total */
            total: number;
        };
        /**
         * VeterinarianResponse
         * @description Proyección mínima para elegir veterinario al reservar.
         *
         *     No trae correo ni teléfono: un cliente necesita el nombre para reservar, no
         *     los datos de contacto del personal.
         */
        VeterinarianResponse: {
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
            role: components["schemas"]["Role"];
        };
        /** VoidPaymentRequest */
        VoidPaymentRequest: {
            /** Reason */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_activity_api_v1_activity_get: {
        parameters: {
            query?: {
                /** @description Filtra por rol */
                role?: components["schemas"]["Role"][] | null;
                /** @description Filtra por acción */
                kind?: components["schemas"]["ActivityKind"][] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appointments_api_v1_appointments_get: {
        parameters: {
            query?: {
                /** @description Filtra por estado */
                status?: components["schemas"]["AppointmentStatus"][] | null;
                /** @description Solo emergencias */
                is_emergency?: boolean | null;
                pet_id?: number | null;
                /** @description Desde */
                starts_after?: string | null;
                /** @description Hasta */
                ends_before?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_appointment_api_v1_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookAppointmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_emergency_api_v1_appointments_emergency_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenEmergencyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_types_api_v1_appointments_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentTypeListResponse"];
                };
            };
        };
    };
    cancel_appointment_api_v1_appointments__appointment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelAppointmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_appointment_api_v1_appointments__appointment_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_appointment_api_v1_appointments__appointment_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_current_user_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_client_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterClientRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slots_of_veterinarian_api_v1_availability_get: {
        parameters: {
            query: {
                /** @description Veterinario consultado */
                veterinarian_id: number;
                /** @description Desde */
                starts_after?: string | null;
                /** @description Hasta */
                ends_before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_slot_api_v1_availability_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishSlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_slots_api_v1_availability_mine_get: {
        parameters: {
            query?: {
                /** @description Desde */
                starts_after?: string | null;
                /** @description Hasta */
                ends_before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_slot_api_v1_availability__slot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                /** @description Busca en nombre, correo y teléfono */
                search?: string | null;
                /** @description Columna, '-' invierte */
                ordering?: string | null;
                /** @description Filtra por estado */
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_clinical_entries_api_v1_medical_records_get: {
        parameters: {
            query: {
                /** @description Mascota consultada */
                pet_id: number;
                /** @description Filtra por tipo */
                kind?: components["schemas"]["EntryKind"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalEntryPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_clinical_entry_api_v1_medical_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddClinicalEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_api_v1_medical_records_attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_api_v1_medical_records__entry_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_api_v1_medical_records__entry_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_api_v1_payments_get: {
        parameters: {
            query?: {
                appointment_id?: number | null;
                /** @description Filtra por medio */
                method?: components["schemas"]["PaymentMethod"] | null;
                /** @description Incluye los anulados */
                include_voided?: boolean;
                /** @description Desde */
                starts_after?: string | null;
                /** @description Hasta */
                ends_before?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_payment_api_v1_payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_report_api_v1_payments_report_get: {
        parameters: {
            query?: {
                /** @description Desde */
                starts_after?: string | null;
                /** @description Hasta */
                ends_before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    void_payment_api_v1_payments__payment_id__void_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidPaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pets_of_owner_api_v1_pets_get: {
        parameters: {
            query: {
                /** @description Cliente dueño de las mascotas */
                owner_id: number;
                /** @description Filtra por estado */
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_pet_api_v1_pets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_pets_api_v1_pets_mine_get: {
        parameters: {
            query?: {
                /** @description Filtra por estado */
                is_active?: boolean | null;
                /** @description Busca en nombre, especie y raza */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_pet_status_api_v1_pets__pet_id__correct_status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectPetStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_pet_status_api_v1_pets__pet_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePetStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staff_api_v1_staff_get: {
        parameters: {
            query?: {
                /** @description Busca en nombre, correo y teléfono */
                search?: string | null;
                /** @description Filtra por estado */
                is_active?: boolean | null;
                /** @description Columna, '-' invierte */
                ordering?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_staff_api_v1_staff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStaffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_emergency_coverage_api_v1_staff__user_id__emergency_coverage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleEmergencyCoverageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_guard_duty_api_v1_staff__user_id__guard_duty_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_user_status_api_v1_users__user_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeUserStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_veterinarians_api_v1_veterinarians_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VeterinarianListResponse"];
                };
            };
        };
    };
}
