// Alias sobre el contrato generado desde OpenAPI. Nadie escribe estas formas a
// mano: si el backend cambia un campo, `pnpm generate:api` lo propaga y el
// build del frontend falla en compilacion en vez de fallar en ejecucion.
import type { components } from './schema'

export type HealthResponse = components['schemas']['HealthResponse']

export type UserResponse = components['schemas']['UserResponse']
export type ClientPageResponse = components['schemas']['ClientPageResponse']
export type AccessTokenResponse = components['schemas']['AccessTokenResponse']
export type LoginRequest = components['schemas']['LoginRequest']
export type ForgotPasswordRequest = components['schemas']['ForgotPasswordRequest']
export type ResetPasswordRequest = components['schemas']['ResetPasswordRequest']
export type MessageResponse = components['schemas']['MessageResponse']
export type IdentityCheckResponse = components['schemas']['IdentityCheckResponse']
export type RegisterClientRequest = components['schemas']['RegisterClientRequest']
export type RegisterStaffRequest = components['schemas']['RegisterStaffRequest']
export type UpdateProfileRequest = components['schemas']['UpdateProfileRequest']
export type RegisterWalkInClientRequest = components['schemas']['RegisterWalkInClientRequest']
export type UpdateClientContactRequest = components['schemas']['UpdateClientContactRequest']
export type VeterinarianResponse = components['schemas']['VeterinarianResponse']
export type VeterinarianListResponse = components['schemas']['VeterinarianListResponse']
export type ActivityResponse = components['schemas']['ActivityResponse']
export type ActivityPageResponse = components['schemas']['ActivityPageResponse']

export type SpecialtyResponse = components['schemas']['SpecialtyResponse']
export type SpecialtyListResponse = components['schemas']['SpecialtyListResponse']
export type SpecialtyCategory = components['schemas']['SpecialtyCategory']
export type AddSpecialtyRequest = components['schemas']['AddSpecialtyRequest']
export type UpdateSpecialtyRequest = components['schemas']['UpdateSpecialtyRequest']
export type AssignVeterinarianSpecialtiesRequest =
  components['schemas']['AssignVeterinarianSpecialtiesRequest']
export type VeterinarianSpecialtiesResponse =
  components['schemas']['VeterinarianSpecialtiesResponse']
export type VeterinarianSpecialtiesListResponse =
  components['schemas']['VeterinarianSpecialtiesListResponse']

export type SpeciesResponse = components['schemas']['SpeciesResponse']
export type PetCatalogResponse = components['schemas']['PetCatalogResponse']
export type ManagedCatalogResponse = components['schemas']['ManagedCatalogResponse']
export type CatalogSpeciesResponse = components['schemas']['CatalogSpeciesResponse']
export type CatalogBreedResponse = components['schemas']['CatalogBreedResponse']
export type UpdateCatalogEntryRequest = components['schemas']['UpdateCatalogEntryRequest']
export type PetResponse = components['schemas']['PetResponse']
export type PetPageResponse = components['schemas']['PetPageResponse']
export type RegisterPetRequest = components['schemas']['RegisterPetRequest']
export type RegisterPetForOwnerRequest = components['schemas']['RegisterPetForOwnerRequest']
export type PetSex = components['schemas']['PetSex']
export type UpdatePetOwnerProfileRequest = components['schemas']['UpdatePetOwnerProfileRequest']
export type UpdatePetClinicalProfileRequest =
  components['schemas']['UpdatePetClinicalProfileRequest']

export type SlotResponse = components['schemas']['SlotResponse']
export type SlotListResponse = components['schemas']['SlotListResponse']
export type ShiftKind = SlotResponse['kind']
export type AssignShiftRequest = components['schemas']['AssignShiftRequest']
export type WeeklyPlanRequest = components['schemas']['WeeklyPlanRequest']
export type ChangeRequestResponse = components['schemas']['ChangeRequestResponse']
export type ChangeRequestListResponse = components['schemas']['ChangeRequestListResponse']
export type ChangeRequestStatus = ChangeRequestResponse['status']
export type CreateChangeRequest = components['schemas']['CreateChangeRequest']
export type ResolveChangeRequest = components['schemas']['ResolveChangeRequest']

export type AppointmentResponse = components['schemas']['AppointmentResponse']
export type AppointmentPageResponse = components['schemas']['AppointmentPageResponse']
export type AppointmentTypeResponse = components['schemas']['AppointmentTypeResponse']
export type AppointmentTypeListResponse = components['schemas']['AppointmentTypeListResponse']
export type BookAppointmentRequest = components['schemas']['BookAppointmentRequest']
export type OpenEmergencyRequest = components['schemas']['OpenEmergencyRequest']
export type OpenWalkInEmergencyRequest = components['schemas']['OpenWalkInEmergencyRequest']
export type OpenTimesResponse = components['schemas']['OpenTimesResponse']
export type DayOpenTimesResponse = components['schemas']['DayOpenTimesResponse']
export type VeterinarianOpenTimesResponse = components['schemas']['VeterinarianOpenTimesResponse']
export type GridSlotResponse = components['schemas']['GridSlotResponse']
export type ScheduleWindowResponse = components['schemas']['ScheduleWindowResponse']
export type SlotStatus = components['schemas']['SlotStatus']

export type ClinicalEntryResponse = components['schemas']['ClinicalEntryResponse']
export type ClinicalEntryPageResponse = components['schemas']['ClinicalEntryPageResponse']
export type AddClinicalEntryRequest = components['schemas']['AddClinicalEntryRequest']
export type EntryKind = components['schemas']['EntryKind']
export type VaccinationCardResponse = components['schemas']['VaccinationCardResponse']
export type VaccinationResponse = components['schemas']['VaccinationResponse']
export type VaccineOptionResponse = components['schemas']['VaccineOptionResponse']
export type VaccineOptionListResponse = components['schemas']['VaccineOptionListResponse']
export type RecordVaccinationRequest = components['schemas']['RecordVaccinationRequest']
export type VaccineCode = components['schemas']['VaccineCode']
export type ClinicalSummaryResponse = components['schemas']['ClinicalSummaryResponse']
export type AttachmentResponse = components['schemas']['AttachmentResponse']

export type PaymentResponse = components['schemas']['PaymentResponse']
export type PaymentPageResponse = components['schemas']['PaymentPageResponse']
export type RegisterPaymentRequest = components['schemas']['RegisterPaymentRequest']
export type PaymentMethod = components['schemas']['PaymentMethod']
export type PaymentReportResponse = components['schemas']['PaymentReportResponse']
export type MethodTotalResponse = components['schemas']['MethodTotalResponse']
export type CreateQrChargeRequest = components['schemas']['CreateQrChargeRequest']
export type QrChargeResponse = components['schemas']['QrChargeResponse']
export type QrChargeStatus = components['schemas']['QrChargeStatus']

export type SubmitReviewRequest = components['schemas']['SubmitReviewRequest']
export type ReviewResponse = components['schemas']['ReviewResponse']
export type VeterinarianReviewsResponse = components['schemas']['VeterinarianReviewsResponse']

export type FileComplaintRequest = components['schemas']['FileComplaintRequest']
export type ComplaintResponse = components['schemas']['ComplaintResponse']
export type ComplaintPageResponse = components['schemas']['ComplaintPageResponse']
export type EvidenceResponse = components['schemas']['EvidenceResponse']

export type ConsentKind = components['schemas']['ConsentKind']
export type ConsentTemplateResponse = components['schemas']['ConsentTemplateResponse']
export type ConsentResponse = components['schemas']['ConsentResponse']
export type AcceptEmergencyRiskRequest = components['schemas']['AcceptEmergencyRiskRequest']
export type RecordInPersonEmergencyRiskRequest =
  components['schemas']['RecordInPersonEmergencyRiskRequest']
export type ConsentStatus = components['schemas']['ConsentStatus']
export type ConsentChannel = components['schemas']['ConsentChannel']
export type ConsentDetails = components['schemas']['ConsentDetailsPayload-Output']
export type ConsentListResponse = components['schemas']['ConsentListResponse']
export type RequestConsentRequest = components['schemas']['RequestConsentRequest']
export type AcceptConsentRequest = components['schemas']['AcceptConsentRequest']
export type DeclineConsentRequest = components['schemas']['DeclineConsentRequest']
export type WaiveConsentRequest = components['schemas']['WaiveConsentRequest']

export type OpenHospitalizationRequest = components['schemas']['OpenHospitalizationRequest']
export type AddNoteRequest = components['schemas']['AddNoteRequest']
export type DischargeRequest = components['schemas']['DischargeRequest']
export type NoteResponse = components['schemas']['NoteResponse']
export type HospitalizationResponse = components['schemas']['HospitalizationResponse']
export type HospitalizationPageResponse = components['schemas']['HospitalizationPageResponse']

export type CareReminderResponse = components['schemas']['CareReminderResponse']
export type CareReminderListResponse = components['schemas']['CareReminderListResponse']
export type NoShowRiskResponse = components['schemas']['NoShowRiskResponse']
export type NoShowRiskListResponse = components['schemas']['NoShowRiskListResponse']
export type PaymentAnomalyResponse = components['schemas']['PaymentAnomalyResponse']
export type PaymentAnomalyListResponse = components['schemas']['PaymentAnomalyListResponse']
export type VeterinarianAlertResponse = components['schemas']['VeterinarianAlertResponse']
export type VeterinarianAlertListResponse = components['schemas']['VeterinarianAlertListResponse']
export type PetOverviewResponse = components['schemas']['PetOverviewResponse']
export type PetOverviewListResponse = components['schemas']['PetOverviewListResponse']
export type ServiceConsumptionResponse = components['schemas']['ServiceConsumptionResponse']
export type ServiceConsumptionListResponse =
  components['schemas']['ServiceConsumptionListResponse']

export type UserRole = UserResponse['role']

export type AppointmentStatus = AppointmentResponse['status']

export type CurrentUserResponse = components['schemas']['CurrentUserResponse']
export type PermissionCode = components['schemas']['Permission']
export type PermissionResponse = components['schemas']['PermissionResponse']
export type PermissionCatalogResponse = components['schemas']['PermissionCatalogResponse']
export type AccessRoleResponse = components['schemas']['AccessRoleResponse']
export type AccessRoleListResponse = components['schemas']['AccessRoleListResponse']
export type CreateAccessRoleRequest = components['schemas']['CreateAccessRoleRequest']
export type UpdateAccessRoleRequest = components['schemas']['UpdateAccessRoleRequest']
export type RoleAssignmentListResponse = components['schemas']['RoleAssignmentListResponse']
export type DocumentLookupResponse = components['schemas']['DocumentLookupResponse']
export type PublicVaccinationCardResponse = components['schemas']['PublicVaccinationCardResponse']
